import type { UiLocale } from '../ui-locale';

type MacroTitle = 'Calories' | 'Protein' | 'Carbs' | 'Fat';

const C = {
  en: {
    welcomeSub: 'One place for meals, training, and next steps from Evo.',
    welcomeName: (name: string) => `Welcome back, ${name}!`,
    missionEyebrow: 'Mission control',
    dailyBriefTitle: 'Evo daily brief',
    dailyBriefSubtitle:
      'Everything here is generated by Evo from your logs — refreshed every few hours and when your day changes.',
    briefHeroSubtitle: 'From your logs — updates when the day changes.',
    progressOnTrack: 'On track',
    progressWatch: 'Watch intake',
    progressInProgress: 'In progress',
    mainInsight: 'Main insight',
    tipNutrition: 'Nutrition',
    tipTraining: 'Training',
    tipRecovery: 'Recovery',
    emptyTitle: 'Evo is waiting for enough context',
    emptyDesc: 'Log at least one meal or workout and Evo will build a focused daily brief.',
    emptyAction: 'Open meals',
    weeklyTitle: 'Weekly Evo review',
    weeklyLast7: 'Last 7 days',
    weeklyPartial: (avail: number, tracked: number) =>
      `Partial weekly review for ${avail}/7 available days (${tracked} tracked).`,
    weeklyEmpty: 'Weekly review will appear after more logs.',
    proTip: 'Focus for the week ahead',
    todayGoals: 'Today goals',
    todayGoalsSub: (date: string) => `Dynamic daily target and progress for ${date}`,
    setGoals: 'Set Goals',
    statCalories: 'Calories',
    statProtein: 'Protein',
    statCarbs: 'Carbs',
    statFat: 'Fat',
    quickActions: 'Quick actions',
    actionMealsTitle: 'Meals',
    actionMealsDesc: 'Describe meal or add photo',
    actionStatsTitle: 'View Stats',
    actionStatsDesc: 'Review history by day',
    actionGoalsTitle: 'Goal Settings',
    actionGoalsDesc: 'Adjust kcal and macros',
    todayMeals: 'Today meals',
    openMeals: 'Open Meals',
    deleteMeal: 'Delete meal',
    noMealsToday: 'No meals logged today',
    logFirstMeal: 'Log first meal',
    quickWorkout: 'Quick add workout',
    fullPage: 'Full page',
    workoutPlaceholder: 'e.g. Running or Push workout',
    minutesPh: 'minutes',
    kcalPh: 'kcal',
    intensityLow: 'Low',
    intensityMedium: 'Medium',
    intensityHigh: 'High',
    adding: 'Adding...',
    addWorkout: 'Add workout',
    dailySteps: 'Daily steps',
    trackedOnly: 'Tracked only',
    stepsPlaceholder: 'Steps today',
    savingSteps: 'Saving steps...',
    saveSteps: 'Save steps',
    todayTraining: 'Today training',
    seeAll: 'See all',
    noWorkoutsToday: 'No workouts yet today.',
    insightBriefFailedTitle: 'Brief did not load',
    insightBriefFailedBody:
      'Evo could not generate today’s brief. Your numbers below are still up to date — try again in a moment.',
    refetchBriefLabel: 'Try again',
    nextActionOpenChatTitle: 'Continue with Evo',
    nextActionOpenChatDesc: 'Chat opens with full context for today so you can pick the next move together.',
    nextActionOpenChatLabel: 'Open Evo chat',
    weeklyNarrativePending: 'Weekly story from Evo will show here once it is ready.',
    sessionsOne: 'session',
    sessionsMany: 'sessions',
    noSessions: 'No sessions',
    metricGoal: 'Goal mode',
    metricMealsToday: 'Meals today',
    mealsLoggedWord: 'meals',
    metricTrainingToday: 'Training today',
    metricSteps7d:
      'Average daily steps over the rolling 7-day window ending on this calendar day (including that day).',
    metricKcalLeft: 'Calories left for today',
    metricProteinLeft: 'Protein left for today',
    statGoalLine: 'Goal:',
    statPercentGoal: (n: string) => `${n}% of goal`,
    evoHintPrefix: 'Evo hint:',
    confirmDeleteMeal: 'Delete this meal entry?',
    workoutTitleMissing: 'Enter workout name before saving.',
    invalidSteps: 'Steps must be between 0 and 120000.',
    scoreNutrition: 'Nutrition',
    scoreTraining: 'Training',
    scoreConsistency: 'Consistency',
    nextStepEyebrow: 'Next step',
    briefShowMore: 'More detail',
    briefShowLess: 'Less',
    reasoningTitle: 'Why Evo thinks this',
    reasoningTriggerShort: 'Why Evo?',
    reasoningIntro:
      'Based on your logs for today: meals, workouts, steps, and your dynamic targets. Full tips below.',
    reasoningTipsHeading: 'Coach tips',
    reasoningDataHeading: 'Signals used',
    addSuggestedMeal: 'Log suggested meal',
    seeOtherOptions: 'More options',
    macroHintLine: (kcalLeft: string, proteinLeft: string) =>
      `About ${kcalLeft} kcal and ${proteinLeft} protein left today (approx.).`,
    statusOnTrack: 'In range',
    statusLow: 'Below target',
    statusHigh: 'Over target',
    statusDone: 'At target',
    consumedLabel: 'Logged',
    targetLabel: 'Target',
    remainingLabel: 'Left',
    overBy: (n: string, unit: string) => `${n} ${unit} over`,
    weeklyExpand: 'Full weekly analysis',
    weeklyCollapse: 'Hide full analysis',
    trendCalories: 'Calories (7D)',
    trendProtein: 'Protein (7D)',
    trendActivity: 'Training kcal (7D)',
    trendPrimaryKcalAvg: (n: string) => `${n} kcal avg`,
    trendPrimaryProteinAvg: (n: string) => `${n} g avg`,
    trendPrimaryTrainingKcalAvg: (n: string) => `${n} kcal avg`,
    trendDeltaVsPriorWeek: (qty: string) => `${qty} vs last week`,
    trendDeltaFlat: 'Roughly flat vs last week',
    trendDeltaNone: 'No prior week logged to compare',
    briefStatGoal: 'Goal',
    briefStatMeals: 'Meals',
    briefStatCalories: 'Calories',
    briefStatActivity: 'Activity',
    briefStatSteps: 'Steps',
    briefTooltipGoal:
      'Your primary goal from settings. Evo uses it to frame calorie targets and coaching tone.',
    briefTooltipMeals: 'Number of meal entries logged for today (this calendar day).',
    briefTooltipActivity: 'Total minutes of structured training logged today (workouts in the app).',
    briefTooltipCalories: 'Calories logged from meals today — food intake only, not exercise “credit”.',
    briefTooltipProtein: 'Protein logged from meals today — helps track progress toward your daily target.',
    briefTooltipSteps: 'Steps recorded for today (activity log / tracker). Does not change meal targets by itself.',
    quickLogExpand: 'Log quickly',
    quickLogCollapse: 'Hide',
    mealTimelineTitle: 'Today',
    suggestedNextMeal: 'Next meal idea',
    noNextMealHint: 'Open meals or chat with Evo for ideas.',
    logSuggestionCta: 'Log meal',
    goalsDayFocus: (macro: string, amount: string, unit: string) =>
      `Widest gap today: ~${amount} ${unit} ${macro} remaining.`,
    stepsSoftTarget: (n: string) => `~${n} step guide`,
    weeklyFallbackNutritionInsight: 'Nutrition signals need a fuller week of meal logs to be specific.',
    weeklyFallbackNutritionFocus: 'Log at least one protein-forward meal before mid-afternoon on training days.',
    weeklyFallbackTrainingInsight: 'Training feedback is thin until workouts are logged more consistently.',
    weeklyFallbackTrainingFocus: 'Plan two short sessions you can repeat weekly and log them right after.',
    weeklyFallbackConsistencyInsight: 'Consistency is hard to judge when logging is uneven across the week.',
    weeklyFallbackConsistencyFocus: 'Pick two anchor meals per day (same rough time) and log them every day.',
  },
  pl: {
    welcomeSub: 'Posiłki, trening i kolejne kroki od Evo w jednym miejscu.',
    welcomeName: (name: string) => `Witaj ponownie, ${name}!`,
    missionEyebrow: 'Pulpit misji',
    dailyBriefTitle: 'Dzienny brief Evo',
    dailyBriefSubtitle:
      'Wszystko tu generuje Evo z Twoich logów — odświeża się co kilka godzin i gdy zmienia się dzień.',
    briefHeroSubtitle: 'Z Twoich logów — odświeża się wraz z dniem.',
    progressOnTrack: 'W normie',
    progressWatch: 'Uważaj na spożycie',
    progressInProgress: 'W toku',
    mainInsight: 'Główny insight',
    tipNutrition: 'Odżywianie',
    tipTraining: 'Trening',
    tipRecovery: 'Regeneracja',
    emptyTitle: 'Evo czeka na więcej danych',
    emptyDesc: 'Zaloguj choć jeden posiłek lub trening — Evo złoży dzienny brief.',
    emptyAction: 'Otwórz posiłki',
    weeklyTitle: 'Tygodniowy przegląd Evo',
    weeklyLast7: 'Ostatnie 7 dni',
    weeklyPartial: (avail: number, tracked: number) =>
      `Częściowy przegląd: ${avail}/7 dostępnych dni (${tracked} z logami).`,
    weeklyEmpty: 'Przegląd pojawi się po większej liczbie wpisów.',
    proTip: 'Skupienie na nadchodzący tydzień',
    todayGoals: 'Cele na dziś',
    todayGoalsSub: (date: string) => `Dynamiczny cel i postęp na ${date}`,
    setGoals: 'Ustaw cele',
    statCalories: 'Kalorie',
    statProtein: 'Białko',
    statCarbs: 'Węglowodany',
    statFat: 'Tłuszcze',
    quickActions: 'Szybkie akcje',
    actionMealsTitle: 'Posiłki',
    actionMealsDesc: 'Opisz posiłek lub dodaj zdjęcie',
    actionStatsTitle: 'Statystyki',
    actionStatsDesc: 'Historia dnia po dniu',
    actionGoalsTitle: 'Cele',
    actionGoalsDesc: 'Kcal i makra',
    todayMeals: 'Dzisiejsze posiłki',
    openMeals: 'Otwórz posiłki',
    deleteMeal: 'Usuń posiłek',
    noMealsToday: 'Brak posiłków na dziś',
    logFirstMeal: 'Dodaj pierwszy posiłek',
    quickWorkout: 'Szybki trening',
    fullPage: 'Pełna strona',
    workoutPlaceholder: 'Np. bieg lub push',
    minutesPh: 'minuty',
    kcalPh: 'kcal',
    intensityLow: 'Niska',
    intensityMedium: 'Średnia',
    intensityHigh: 'Wysoka',
    adding: 'Dodawanie…',
    addWorkout: 'Dodaj trening',
    dailySteps: 'Kroki dziś',
    trackedOnly: 'Tylko śledzone',
    stepsPlaceholder: 'Kroki na dziś',
    savingSteps: 'Zapisywanie kroków…',
    saveSteps: 'Zapisz kroki',
    todayTraining: 'Trening dziś',
    seeAll: 'Zobacz wszystko',
    noWorkoutsToday: 'Brak treningów na dziś.',
    insightBriefFailedTitle: 'Brief się nie wczytał',
    insightBriefFailedBody:
      'Evo nie zdążył złożyć dzisiejszego briefu. Liczby niżej są aktualne — spróbuj ponownie za chwilę.',
    refetchBriefLabel: 'Spróbuj ponownie',
    nextActionOpenChatTitle: 'Dokończ z Evo',
    nextActionOpenChatDesc: 'Czat z pełnym kontekstem dnia — ustalicie następny ruch razem.',
    nextActionOpenChatLabel: 'Otwórz czat Evo',
    weeklyNarrativePending: 'Tygodniowa narracja Evo pojawi się tu, gdy będzie gotowa.',
    sessionsOne: 'sesja',
    sessionsMany: 'sesje',
    noSessions: 'Brak sesji',
    metricGoal: 'Tryb celu',
    metricMealsToday: 'Posiłki dziś',
    mealsLoggedWord: 'posiłków',
    metricTrainingToday: 'Trening dziś',
    metricSteps7d:
      'Średnia dzienna kroków z ostatnich 7 dni kończących się tym dniem kalendarzowym (włącznie z nim).',
    metricKcalLeft: 'Pozostałe kcal',
    metricProteinLeft: 'Pozostałe białko',
    statGoalLine: 'Cel:',
    statPercentGoal: (n: string) => `${n}% celu`,
    evoHintPrefix: 'Podpowiedź Evo:',
    confirmDeleteMeal: 'Usunąć ten wpis posiłku?',
    workoutTitleMissing: 'Podaj nazwę treningu przed zapisem.',
    invalidSteps: 'Kroki muszą być między 0 a 120000.',
    scoreNutrition: 'Odżywianie',
    scoreTraining: 'Trening',
    scoreConsistency: 'Konsekwencja',
    nextStepEyebrow: 'Kolejny krok',
    briefShowMore: 'Więcej',
    briefShowLess: 'Mniej',
    reasoningTitle: 'Dlaczego Evo tak uważa?',
    reasoningTriggerShort: 'Dlaczego Evo?',
    reasoningIntro:
      'Na podstawie dzisiejszych logów: posiłki, trening, kroki oraz dynamiczne cele. Pełne wskazówki niżej.',
    reasoningTipsHeading: 'Wskazówki coacha',
    reasoningDataHeading: 'Użyte sygnały',
    addSuggestedMeal: 'Dodaj sugerowany posiłek',
    seeOtherOptions: 'Zobacz inne opcje',
    macroHintLine: (kcalLeft: string, proteinLeft: string) =>
      `Zostało ok. ${kcalLeft} kcal i ${proteinLeft} białka (orientacyjnie).`,
    statusOnTrack: 'W zakresie',
    statusLow: 'Poniżej celu',
    statusHigh: 'Powyżej celu',
    statusDone: 'Cel osiągnięty',
    consumedLabel: 'Zalogowane',
    targetLabel: 'Cel',
    remainingLabel: 'Zostało',
    overBy: (n: string, unit: string) => `+${n} ${unit} ponad`,
    weeklyExpand: 'Pełna analiza tygodnia',
    weeklyCollapse: 'Zwiń analizę',
    trendCalories: 'Kalorie (7D)',
    trendProtein: 'Białko (7D)',
    trendActivity: 'Kcal z treningu (7D)',
    trendPrimaryKcalAvg: (n: string) => `${n} kcal śr.`,
    trendPrimaryProteinAvg: (n: string) => `${n} g śr.`,
    trendPrimaryTrainingKcalAvg: (n: string) => `${n} kcal śr.`,
    trendDeltaVsPriorWeek: (qty: string) => `${qty} wzgl. poprz. tyg.`,
    trendDeltaFlat: 'Bez wyraźnej zmiany vs poprz. tydzień',
    trendDeltaNone: 'Brak danych z poprz. tygodnia do porównania',
    briefStatGoal: 'Cel',
    briefStatMeals: 'Posiłki',
    briefStatCalories: 'Kalorie',
    briefStatActivity: 'Aktywność',
    briefStatSteps: 'Kroki',
    briefTooltipGoal:
      'Główny cel z ustawień — Evo dobiera ton i ramę celów kalorycznych względem tego trybu.',
    briefTooltipMeals: 'Liczba zalogowanych posiłków na dziś (bieżący dzień kalendarzowy).',
    briefTooltipActivity: 'Łączny czas treningu zapisanego dziś w aplikacji (sesje strukturalne).',
    briefTooltipCalories: 'Kalorie z zalogowanych posiłków dziś — sama dieta, bez „kredytu” z ruchu.',
    briefTooltipProtein: 'Białko z posiłków dziś — śledzisz realizację dziennego celu białkowego.',
    briefTooltipSteps: 'Kroki zapisane na dziś (log aktywności / opaska). Same kroki nie zmieniają celów makro.',
    quickLogExpand: 'Szybki zapis',
    quickLogCollapse: 'Ukryj',
    mealTimelineTitle: 'Dziś',
    suggestedNextMeal: 'Pomysł na kolejny posiłek',
    noNextMealHint: 'Otwórz posiłki lub czat z Evo po inspirację.',
    logSuggestionCta: 'Dodaj posiłek',
    goalsDayFocus: (macro: string, amount: string, unit: string) =>
      `Największa luka dziś: ~${amount} ${unit} ${macro} do celu.`,
    stepsSoftTarget: (n: string) => `~${n} kroków (orientacyjnie)`,
    weeklyFallbackNutritionInsight: 'Za mało logów posiłków, by ocenić odżywianie precyzyjnie.',
    weeklyFallbackNutritionFocus: 'W dni treningowe dodaj jeden posiłek białkowy przed południem.',
    weeklyFallbackTrainingInsight: 'Mało zapisanych treningów — trudno ocenić obciążenie tygodnia.',
    weeklyFallbackTrainingFocus: 'Zaplanuj dwie krótkie sesje do powtórzenia co tydzień i od razu je loguj.',
    weeklyFallbackConsistencyInsight: 'Logowanie jest nierówne — wzorce tygodnia są tylko częściowe.',
    weeklyFallbackConsistencyFocus: 'Ustal dwa kotwicowe posiłki dziennie (podobna pora) i loguj je codziennie.',
  },
} as const;

export type DashboardStrings = (typeof C)['en'];

export function getDashboardStrings(locale: UiLocale): DashboardStrings {
  return (locale === 'pl' ? C.pl : C.en) as DashboardStrings;
}

/** Maps GraphQL `DashboardNextActionTarget` to an in-app route. */
export function resolveDashboardInsightNextActionPath(target: string): string {
  switch (String(target || '').toUpperCase()) {
    case 'MEALS':
      return '/meals';
    case 'WORKOUTS':
      return '/workouts';
    case 'CHAT_COACH':
      return '/chat?channel=COACH';
    case 'STATS':
      return '/stats';
    case 'GOALS':
      return '/goals';
    default:
      return '/meals';
  }
}

export function buildDashboardGoalHoverHint(
  locale: UiLocale,
  input: { title: MacroTitle; value: number; goal: number; unit: 'kcal' | 'g' }
): string {
  const { title, value, goal, unit } = input;
  const pl = locale === 'pl';
  if (!goal || goal <= 0) {
    return pl ? 'Dodaj więcej danych z dnia — wtedy dam precyzyjną rekomendację.' : 'Add more day data and I will provide a precise recommendation.';
  }
  const ratio = value / goal;
  const remaining = Math.max(0, goal - value);

  if (title === 'Calories') {
    if (ratio > 1.05)
      return pl
        ? `Powyżej celu o ok. ${Math.round(value - goal)} ${unit}. Następny posiłek lżejszy i białkowy.`
        : `You are over by ${Math.round(value - goal)} ${unit}. Keep next meal lighter and protein-focused.`;
    if (ratio < 0.65)
      return pl
        ? `Zostało ok. ${Math.round(remaining)} ${unit}. Dodaj zbalansowany posiłek, żeby nie niedożywiać.`
        : `You still have around ${Math.round(remaining)} ${unit}. Add a balanced meal to avoid underfueling.`;
    return pl ? 'Tempo kalorii OK. Kontroluj porcje i domknij dzień czysto.' : 'Calorie pace is solid. Keep portions controlled and close the day clean.';
  }
  if (title === 'Protein') {
    if (ratio < 0.7)
      return pl
        ? `Zostało ok. ${Math.round(remaining)} ${unit} białka. Postaw na chude źródła (kurczak, ryby, jogurt).`
        : `Around ${Math.round(remaining)} ${unit} left. Prioritize lean protein now (skyr, chicken, fish).`;
    if (ratio > 1.15)
      return pl
        ? 'Białko już ponad cel — następny posiłek: więcej warzyw i jakościowych węgli.'
        : 'Protein is already above target. Shift next meal toward vegetables and quality carbs.';
    return pl ? 'Białko w dobrym tempie. Jedna umiarkowana porcja powinna domknąć cel.' : 'Protein pace looks good. One moderate protein portion should close the target.';
  }
  if (title === 'Carbs') {
    if (ratio < 0.7)
      return pl
        ? `Zostało ok. ${Math.round(remaining)} ${unit} węgli. Dobre źródła wokół aktywności (ryż, płatki, ziemniaki).`
        : `About ${Math.round(remaining)} ${unit} left. Use quality carbs around activity (rice, oats, potatoes).`;
    if (ratio > 1.1)
      return pl
        ? 'Węgle wysoko — następny posiłek niżej w węglach, wyżej w białku i błonniku.'
        : 'Carbs are running high. Keep next meal lower-carb and higher in protein/fiber.';
    return pl ? 'Węgle w normie. Trzymaj się głównie pełnych produktów.' : 'Carbs are on track. Keep sources mostly whole-food and easy to digest.';
  }
  if (title === 'Fat') {
    if (ratio < 0.7)
      return pl
        ? `Zostało ok. ${Math.round(remaining)} ${unit} tłuszczu. Zdrowe tłuszcze: oliwa, orzechy, ryby tłuste.`
        : `About ${Math.round(remaining)} ${unit} left. Prefer healthy fats like olive oil, nuts, seeds, or fatty fish.`;
    if (ratio > 1.1)
      return pl
        ? 'Tłuszcz ponad cel — następny posiłek chudszy, uważaj na ukryte oleje i sosy.'
        : 'Fat is above target. Keep next meal leaner and watch hidden oils/sauces.';
    return pl ? 'Tłuszcze wyglądają OK. Stabilne porcje i dobre źródła.' : 'Fat looks balanced. Keep quality sources and stable portions.';
  }
  return pl ? 'Brak danych do podpowiedzi.' : 'No hint for this metric.';
}
