'use client';

import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

export default function ChatMarkdown({ content }: { content: string }) {
  const normalizedContent = content
    // Fix malformed ordered list markers generated by AI: "1." on its own line.
    .replace(/(^|\n)(\d+)\.\s*\n+(?=\S)/g, '$1$2. ')
    // Fix malformed bullet markers generated on separate lines.
    .replace(/(^|\n)-\s*\n+(?=\S)/g, '$1- ')
    // Compress excessive empty lines in chat bubbles.
    .replace(/\n{3,}/g, '\n\n');

  return (
    <ReactMarkdown
      remarkPlugins={[remarkGfm]}
      components={{
        p: ({ children }) => <p className="m-0 text-sm leading-relaxed text-text-primary">{children}</p>,
        strong: ({ children }) => <strong className="font-semibold text-text-primary">{children}</strong>,
        em: ({ children }) => <em className="italic text-text-secondary">{children}</em>,
        ul: ({ children }) => <ul className="my-1 list-disc pl-4 space-y-1 text-sm text-text-primary">{children}</ul>,
        ol: ({ children }) => <ol className="my-1 list-decimal pl-4 space-y-1 text-sm text-text-primary">{children}</ol>,
        li: ({ children }) => <li className="leading-relaxed marker:text-text-muted">{children}</li>,
        code: ({ children }) => (
          <code className="rounded bg-surface-elevated px-1 py-0.5 text-[0.85em] text-text-primary">{children}</code>
        ),
      }}
    >
      {normalizedContent.trim()}
    </ReactMarkdown>
  );
}
